global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cassandra-exporter'
    static_configs:
      - targets: ['cassandra-exporter:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'cassandra-jmx'
    static_configs:
      - targets: ['cassandra:7199']
    scrape_interval: 15s
