version: '3.8'

services:
   cassandra1:
    image: cassandra:5.0.3
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=rayan
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=cassandra1
    ports:
      - "9042:9042"
      - "7199:7199"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10

   cassandra2:
    image: cassandra:5.0.3
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=rayan
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=cassandra2
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
   cassandra-exporter:
    image: criteord/cassandra_exporter:2.3
    container_name: cassandra-exporter
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_EXPORTER_CONFIG_host=cassandra1:7199
      - HTTP_PORT=8080
    depends_on:
      cassandra2:
        condition: service_healthy
   prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - cassandra-exporter

   grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    #   - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

# volumes:
#   prometheus_data:
#   grafana_data:
