version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.3
    container_name: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - ./keystore.jks:/etc/cassandra/keystore.jks
      - ./truststore.jks:/etc/cassandra/truststore.jks
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_CLUSTER_NAME=SecureCluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch