version: '3.8'

services:
  # Old Data Center (DC1)
  dc1_n1:
    image: cassandra:5.0.3
    container_name: dc1_n1
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_CLUSTER_NAME=MigrationCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=dc1_n1,dc2_n1
    ports:
      - "9042:9042"

  dc1_n2:
    image: cassandra:5.0.3
    container_name: dc1_n2
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_CLUSTER_NAME=MigrationCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=dc1_n1,dc2_n1
    depends_on:
      - dc1_n1

  # New Data Center (DC2)
  dc2_n1:
    image: cassandra:5.0.3
    container_name: dc2_n1
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_CLUSTER_NAME=MigrationCluster
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=dc1_n1,dc2_n2

  dc2_n2:
    image: cassandra:5.0.3
    container_name: dc2_n2
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_CLUSTER_NAME=MigrationCluster
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=dc1_n1,dc2_n1
    depends_on:
      - dc2_n1
