version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.3
    container_name: cassandra
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10