version: '3.8'

services:
  cassandra-node-1:
    image: cassandra:5.0.3
    container_name: cassandra-node-1
    environment:
      - CASSANDRA_CLUSTER_NAME=WeightedCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256  # High capacity node (stores more data)
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-node-1-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10

  cassandra-node-2:
    image: cassandra:5.0.3
    container_name: cassandra-node-2
    depends_on:
      - cassandra-node-1
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1
      - CASSANDRA_CLUSTER_NAME=WeightedCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128  # Medium capacity node
    volumes:
      - ./cassandra-node-2-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10

  cassandra-node-3:
    image: cassandra:5.0.3
    container_name: cassandra-node-3
    depends_on:
      - cassandra-node-1
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1
      - CASSANDRA_CLUSTER_NAME=WeightedCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=64   # Low capacity node
    volumes:
      - ./cassandra-node-3-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10