version: '3.8'

services:
  cassandra-node-strong:
    image: cassandra:5.0.3
    container_name: cassandra-node-strong
    environment:
      - CASSANDRA_CLUSTER_NAME=WeightedCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256  # High capacity node (stores more data)
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-node-strong:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10

  cassandra-node-weak:
    image: cassandra:5.0.3
    container_name: cassandra-node-weak
    depends_on:
      - cassandra-node-strong
    environment:
      - CASSANDRA_SEEDS=cassandra-node-strong
      - CASSANDRA_CLUSTER_NAME=WeightedCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=32  # low capacity node
    volumes:
      - ./cassandra-node-weak:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 10s
      timeout: 5s
      retries: 10